apiVersion: v1
kind: Service
metadata:
  labels:
    app: csgo
  name: csgo
spec:
  externalIPs:
    - {{ .Values.server_ip }}
  ports:
  - name: source-server
    port: 27015
    protocol: UDP
    targetPort: 27015
  selector:
    app: csgo
  type: NodePort
